# -*- coding: utf-8 -*-
"""Primeiro_Metodo-A3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bbcvlWPFMYpLGhioxvREnMRK4KRGolgv
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Carregando a base de dados
df = pd.read_csv('winequality-red.csv')

# Definindo as variaveis
X = df.drop('quality', axis=1)
y = df[['quality']]
X.head()
#y.head()

from sklearn.model_selection import train_test_split

# Treino e Teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


from sklearn.linear_model import LinearRegression
modelo = LinearRegression()

#  Treinando
modelo.fit(X_train,y_train)

# Previsão
y_pred = modelo.predict(X_test)

# Avaliando o modelo
predictions = modelo.predict(X_test)

from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

# Visualização
plt.scatter(y_test, y_pred)
plt.xlabel('Valores reais')
plt.ylabel('Valores previstos')
plt.show()